-- Estrutura do H2 (idempotente - roda a cada inicio com sql.init.mode=always)
CREATE TABLE IF NOT EXISTS agendamento (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente        BIGINT NOT NULL,
    id_profissional   BIGINT NOT NULL,
    data_agendada     TIMESTAMP NOT NULL,
    status            VARCHAR(50) NOT NULL,
    telefone_cliente  VARCHAR(30),
    criado_em         TIMESTAMP NOT NULL,
    atualizado_em     TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS template_mensagem (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status   VARCHAR(50) NOT NULL UNIQUE,
    template VARCHAR(1000) NOT NULL
);